baseURL = "https://mytech.wiki"
languageCode = "en-us"
title = "Technical notes"
theme = "geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableGitInfo = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocRepo = "https://github.com/benmezger/technotes"
  geekdocEditPath = "edit/main/exampleSite/content"
