[build]
publish = "public"
command = "make all"

[context.production.environment]
HUGO_VERSION = "0.84.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.develop.environment]
HUGO_VERSION = "0.84.0"
HUGO_ENABLEGITINFO = "true"
